local module = {}

module["Lynx"] = {
	["eat_interval"] = 4,
	["eat_duration"] = 2,
	["range"] = 5,
	["patrol_interval"] = 7,
	["patrol_duration"] = 3,
}

module["Kitsune"] = {
	["eat_interval"] = 4,
	["eat_duration"] = 2,
	["range"] = 4,
	["patrol_interval"] = 3,
	["patrol_duration"] = 3,
}

module["Comodork"] = {
	["eat_interval"] = 5,
	["eat_duration"] = 1,
	["range"] = 3,
	["patrol_interval"] = 8,
	["patrol_duration"] = 3,
}

module["Zothz"] = {
	["eat_interval"] = 5,
	["eat_duration"] = 2,
	["range"] = 10,
	["patrol_interval"] = 5,
	["patrol_duration"] = 3,
}

return module
