local module = {}

module["Fox"] = {
	["eat_interval"] = 2,
	["eat_duration"] = 3,
	["range"] = 9,
	["patrol_interval"] = 7,
	["patrol_duration"] = 3,
	["base"] = 2,
}

module["Panda"] = {
	["eat_interval"] = 4,
	["eat_duration"] = 3,
	["range"] = 9,
	["patrol_interval"] = 3,
	["patrol_duration"] = 3,
	["base"] = 4,
}

module["Elephant"] = {
	["eat_interval"] = 6,
	["eat_duration"] = 3,
	["range"] = 9,
	["patrol_interval"] = 8,
	["patrol_duration"] = 3,
	["base"] = 6,
}

module["Hippo"] = {
	["eat_interval"] = 6,
	["eat_duration"] = 5,
	["range"] = 9,
	["patrol_interval"] = 8,
	["patrol_duration"] = 3,
	["base"] = 6,
}

module["Rhino"] = {
	["eat_interval"] = 6,
	["eat_duration"] = 5,
	["range"] = 9,
	["patrol_interval"] = 8,
	["patrol_duration"] = 3,
	["base"] = 6,
}
--
return module
