local ReplicatedStorage = game:GetService("ReplicatedStorage")
local PetTypes = require(ReplicatedStorage.Pets.PetTypes)
return {
	["Fox"] = {
		petProg = 0,
		isInvoked = true,
		avaiblePoints = 0,
		petName = "Fox",
		petLvl = 1,
		petStats = {
			["Health"] = 1,
			["Melee"] = 1,
			["Stamina"] = 1,
		},
		rarity = "common",
	},

	["Hippo"] = {
		petProg = 0,
		isInvoked = true,
		avaiblePoints = 0,
		petName = "Hippo",
		petLvl = 1,
		petStats = {
			["Health"] = 1,
			["Melee"] = 1,
			["Stamina"] = 1,
		},
		rarity = "common",
	},
	["Rhino"] = {
		petProg = 0,
		isInvoked = true,
		avaiblePoints = 0,
		petName = "Rhino",
		petLvl = 1,
		petStats = {
			["Health"] = 1,
			["Melee"] = 1,
			["Stamina"] = 1,
		},
		rarity = "common",
	},
	["Elephant"] = {
		petProg = 0,
		isInvoked = true,
		avaiblePoints = 0,
		petName = "Elephant",
		petLvl = 1,
		petStats = {
			["Health"] = 1,
			["Melee"] = 1,
			["Stamina"] = 1,
		},
		rarity = "common",
	},
	["Panda"] = {
		petProg = 0,
		isInvoked = true,
		avaiblePoints = 0,
		petName = "Panda",
		petLvl = 1,
		petStats = {
			["Health"] = 1,
			["Melee"] = 1,
			["Stamina"] = 1,
		},
		rarity = "common",
	},
} :: PetTypes.Petsinformation
